name: theme_manager_xample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.2+1

environment:
  sdk: ">=2.13.1 <3.0.0" #Dart SDK 9-Mar-2021

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  theme_manager:
    path: ../

dev_dependencies:
  test: ^1.17.7

flutter:
  uses-material-design: true
