name: theme_manager_xample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3+1

environment:
  sdk: ">=2.14.0 <3.0.0" #Dart SDK 12-SEP-2021
  flutter: ">=2.5.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  theme_manager:
    path: ../

dev_dependencies:
  test: ^1.18.2

flutter:
  uses-material-design: true
