name: theme_manager
description: Manages light and dark themes
version: 0.4.1
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0" #Dart SDK 12-SEP-2021
  flutter: ">=2.5.0"

dependencies:
  app_exception:
    git:
      url: https://github.com/GitHubStuff/app_exception.git
  dartz: ^0.10.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  font_awesome_flutter: ^9.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  test: ^1.18.2

flutter:
  uses-material-design: true
