name: theme_manager
description: Manages light and dark themes
version: 0.5.1+1
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.4 <3.0.0" #Dart SDK 2021-10-15
  flutter: ">=2.5.3"

dependencies:
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  dartz: ^0.10.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  font_awesome_flutter: ^9.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  test: ^1.20.1

flutter:
  uses-material-design: true
